steamKey: "{{ lookup('env', 'STEAM_API_KEY', default=Undefined) }}"
mods:
- screepsmod-mongo
- screepsmod-admin-utils
- screepsmod-auth
- screepsmod-tickrate
- screepsmod-features
bots:
  simplebot: "screepsbot-zeswarm"
localMods: ./mods
serverConfig:
  welcomeText:  |
    <div>
      Welcome text goes here? Hello and welcome?
    </div>
  tickRate: 1000