steamKey: "{{ lookup('env', 'STEAM_API_KEY', default=Undefined) }}"
env:
  backend:
    SERVER_PASSWORD: "{{ lookup('env', 'SCREEPS_SERVER_PASSWORD', default=Undefined) }}"
  shared:
    MONGO_HOST: mongo
    REDIS_HOST: redis
mods:
- screepsmod-mongo
- screepsmod-admin-utils
- screepsmod-auth
- screepsmod-tickrate
- screepsmod-features
bots:
  simplebot: "screepsbot-zeswarm"
pinnedPackages:
  ssri: 8.0.1
  cacache: 16.1.3
  passport-steam: 1.0.17
localMods: ./mods # TODO
serverConfig:
  welcomeText:  |
    <div>
      Welcome text goes here
      <br>
      Samma på Svenska
    </div>
  tickRate: 1000