- hosts: configurable-servers
  remote_user: root
  become: yes

  vars:
    base_domain: "{{ lookup('env', 'BASE_DOMAIN') }}"
    acme_email: "{{ lookup('env', 'ACME_EMAIL') }}"
    rclone:
      config_path: "{{ lookup('env', 'RCLONE_CONFIG_FILE_PATH') }}"
      backups_remote: "{{ lookup('env', 'RCLONE_BACKUP_REMOTE_NAME') }}"

  roles:
    - name: basic
      tags: [basic]
    - name: rclone
      tags: [rclone]
    - name: docker
      tags: [docker]
    - name: traefik
      tags: [traefik]
    - name: screeps-server
      tags: [screeps-server]
    - name: tandoor
      tags: [tandoor]
    - name: factorio-maps
      tags: [factorio-maps]
