- name: Set timezone to Europe/Helsinki
  community.general.timezone:
    name: Europe/Helsinki

- name: Ensure Pip is installed
  apt:
    name: python3-pip

- name: Ensure Ansible Pip dependencies are installed
  pip:
    name: requests