services:
  traefik:
    image: traefik:latest
    container_name: "traefik"
    ports:
      - "443:443"
    volumes:
      - "/usr/local/lib/traefik/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/usr/local/etc/traefik:/etc/traefik/"

networks:
  default:
    external:
      name: traefik
