services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - "/usr/local/lib/traefik/acme:/acme"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/usr/local/etc/traefik:/etc/traefik/"

networks:
  default:
    name: traefik
    external: true
